=== yuhattor/BranchProtectionBot/config/protection_rules_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "required_status_checks": {
            "type": "object",
            "properties": {
                "strict": {
                    "type": "boolean"
                },
                "contexts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "enforce_admins": {
            "type": "boolean"
        },
        "required_pull_request_reviews": {
            "type": "object",
            "properties": {
                "dismissal_restrictions": {
                    "type": "object",
                    "properties": {
                        "users": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "teams": {
                            "type": "array"
                        },
                        "apps": {
                            "type": "array"
                        }
                    }
                },
                "dismiss_stale_reviews": {
                    "type": "boolean"
                },
                "require_code_owner_reviews": {
                    "type": "boolean"
                },
                "required_approving_review_count": {
                    "type": "integer"
                }
            }
        },
        "restrictions": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teams": {
                    "type": "array"
                },
                "apps": {
                    "type": "array"
                }
            }
        },
        "required_linear_history": {
            "type": "boolean"
        },
        "allow_force_pushes": {
            "type": "boolean"
        },
        "allow_deletions": {
            "type": "boolean"
        }
    }
}

=== yuhattor/BranchProtectionBot/config/protection_rules.json
{
    "required_status_checks": {
        "strict": true,
        "contexts": [
            "build-and-deploy"
        ]
    },
    "enforce_admins": true,
    "required_pull_request_reviews": {
        "dismissal_restrictions": {
            "users": [
                "yuhattor"
            ],
            "teams": [],
            "apps": []
        },
        "dismiss_stale_reviews": true,
        "require_code_owner_reviews": true,
        "required_approving_review_count": 2
    },
    "restrictions": {
        "users": [
            "yuhattor"
        ],
        "teams": [],
        "apps": []
    },
    "required_linear_history": true,
    "allow_force_pushes": true,
    "allow_deletions": true
}
